# coding: utf-8

"""
    Unit OpenAPI specifications

    An OpenAPI specifications for unit-sdk clients

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "unit-openapi-python-sdk"
VERSION = "0.0.1"
PYTHON_REQUIRES = ">= 3.8"
REQUIRES = [
    "urllib3 >= 1.25.3, < 3.0.0",
    "python-dateutil >= 2.8.2",
    "pydantic >= 2",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="Unit python SDK based on OpenAPI specifications",
    author="Unit",
    author_email="engineering@unit.co",
    url="https://github.com/unit-finance/unit-openapi-python-sdk",
    license="Mozilla Public License 2.0",
    keywords=["OpenAPI", "OpenAPI-Generator", "Unit", "Unit OpenAPI specifications", "Unit SDK", "Unit python SDK", "Unit python openAPI SDK"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test"]),
    include_package_data=True,
    long_description_content_type='text/markdown',
    long_description="""\
    A python SDK generated based on OpenAPI specifications for Unit clients
    """,  # noqa: E501
    package_data={"unit_openapi_python_sdk": ["py.typed"]},
)
